CREATE INDEX userId_id ON USR  USING BTREE (userId);
CREATE INDEX password_id ON USR  USING BTREE (password);
CREATE INDEX name_id ON USR  USING BTREE (name);
CREATE INDEX dateOfBirth_id ON USR  USING BTREE (dateOfBirth);

CREATE INDEX userId2_id ON WORK_EXPR  USING BTREE (userId);
CREATE INDEX company_id ON WORK_EXPR  USING BTREE (company);
CREATE INDEX role_id ON WORK_EXPR  USING BTREE (role);
CREATE INDEX location_id ON WORK_EXPR  USING BTREE (location );
CREATE INDEX startDate_id ON WORK_EXPR  USING BTREE (startDate);
CREATE INDEX endDate_id ON WORK_EXPR  USING BTREE (endDate);

CREATE INDEX userId3_id ON EDUCATIONAL_DETAILS  USING BTREE (userId);
CREATE INDEX instituitionName_id ON EDUCATIONAL_DETAILS  USING BTREE (instituitionName);
CREATE INDEX major_id ON EDUCATIONAL_DETAILS  USING BTREE (major);
CREATE INDEX degree_id ON EDUCATIONAL_DETAILS  USING BTREE (degree);
CREATE INDEX startdate_id ON EDUCATIONAL_DETAILS  USING BTREE (startdate);
CREATE INDEX enddate_id ON EDUCATIONAL_DETAILS  USING BTREE (enddate);


CREATE INDEX msgId_id ON MESSAGE  USING BTREE (msgId);
CREATE INDEX senderId_id ON MESSAGE  USING BTREE (senderId );
CREATE INDEX receiverId_id ON MESSAGE  USING BTREE (receiverId);
CREATE INDEX contents_id ON MESSAGE  USING BTREE (contents);
CREATE INDEX sendTime_id ON MESSAGE  USING BTREE (sendTime);
CREATE INDEX status_id ON MESSAGE  USING BTREE (status);
CREATE INDEX deleteStatus_id ON MESSAGE  USING BTREE (deleteStatus);

CREATE INDEX userId4_id ON  CONNECTION_USR  USING BTREE (userId);
CREATE INDEX connectionId_id ON  CONNECTION_USR  USING BTREE (connectionId);
CREATE INDEX status_id ON  CONNECTION_USR  USING BTREE (status);