COPY USR FROM '/home/csmajs/jli675/USR.csv' WITH DELIMITER ',' CSV HEADER;
COPY WORK_EXPR FROM '/home/csmajs/jli675/Work_Ex.csv' WITH DELIMITER ',' CSV HEADER;
COPY EDUCATIONAL_DETAILS FROM '/home/csmajs/jli675/Edu_Det.csv' WITH DELIMITER ',' CSV HEADER;
COPY MESSAGE FROM '/home/csmajs/jli675/Message.csv' WITH DELIMITER ',' CSV HEADER;
COPY CONNECTION_USR FROM '/home/csmajs/jli675/Connection.csv' WITH DELIMITER ',' CSV HEADER;
