COPY USR FROM '/home/csmajs/zxu134/USR.csv' WITH DELIMITER ',' CSV HEADER;
COPY WORK_EXPR FROM '/home/csmajs/zxu134/Work_Ex.csv' WITH DELIMITER ',' CSV HEADER;
COPY EDUCATIONAL_DETAILS FROM '/home/csmajs/zxu134/Edu_Det.csv' WITH DELIMITER ',' CSV HEADER;
COPY MESSAGE FROM '/home/csmajs/zxu134/Message.csv' WITH DELIMITER ',' CSV HEADER;
COPY CONNECTION_USR FROM '/home/csmajs/zxu134/Connection.csv' WITH DELIMITER ',' CSV HEADER;