
CREATE LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION intsertNum()
RETURNS "trigger" AS
$BODY$
BEGIN
NEW.msgId := nextval('msgId_seq');
RETURN NEW;
END;
$BODY$
LANGUAGE plpgsql VOLATILE;

CREATE TRIGGER checker BEFORE INSERT
ON MESSAGE FOR EACH ROW
EXECUTE PROCEDURE intsertNum();


